language: cpp

git:
  depth: 1
  
sudo: required
dist: trusty

install:
  - brew install glew
  - brew install clang-format
  - brew install qt
  
script:
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  - source ~/.bash_profile
  - export LDFLAGS="-L/usr/local/opt/qt/lib"
  - export CPPFLAGS="-I/usr/local/opt/qt/include"
  - cd DummyGui
  - qmake DummyGui.pro
  - make
  - cd ..
  - cd DummyTesting
  - qmake DummyTesting.pro
  - make
  - ./DummyTesting.app/Contents/MacOS/DummyTesting
  
matrix:
  include:
      - os: osx
        osx_image: xcode8.3

